# PCA

## SVD

Singular Value Decomposition:

Nó chỉ đơn thuần nói về việc: một ma trận $A$ bất kỳ nào đều có thể phân tách thành 3 ma trận $U, D, V$.
> $A = U.D.V^T$
> 
> Trong đó:
> 
> *$U, V$* là hai <u>ma trận trực giao (Orthogonal Matrix)</u>, chứa các Vecto riêng(Eigenvector) của $A.A^T , A^T.A$
>> ma trận trực giao thường được ứng dụng trong phép quay với một số tính chất đặc biệt như:
>>> - Định thức(Determination) = $\pm1$ (định thức được dùng để diễn tả mức độ nén "squish - stretch" của một đơn vị diện tích khi thực hiện một phép <u>biến đổi(transformation)</u> ma ma trận từ cơ sở này sang cơ sở khác), điều đó đồng nghĩa là khi thực hiện phép biến đổi với Orthogonal Matrix, sẽ được bảo toàn về độ dài của vector cũng như góc giữa các vector. <br> Tham khảo: [Determinant - 3Blue1Brown](https://youtu.be/Ip3X9LOh2dk),
>>> - $A^T = A^{-1}$ -> việc biến đổi ma trận chuyển vị sẽ đỡ tốn kém rất nhiều so với việc phải tính toán toàn ma trận nghịch đảo => có thể dùng $A^T$ thay cho $A^{-1}$ trong nhiều tình huống
>>
>> Trị riêng, Vecto riêng (Eigenvalue, Eigenvector) của một ma trận được diễn tả qua công thức: $A.\vec{v} = \lambda.\vec{v}$<br>
>>> - Tức là, tại một Không gian vecto $B$, khi thực hiện phép biến đổi sang không gian vecto $A$ thì mọi vecto của không gian vecto đó sẽ bị thay đổi hướng(direction) trừ các vecto đặc biêt $\vec{v}$, các vecto đặc biệt $\vec{v}$ này gọi là *eigenvector* và tương ứng với mỗi *eigenvector* sẽ là một *eigenvalue*,  *eigenvalue* là một đại lượng thể hiện độ stretch của một *eigenvector* ở không gian mới <br>Tham khảo: [Eigenvectors and eigenvalues - 3Blue1Brown](https://youtu.be/PFDu9oVAE-g) <br>
>>> - ứng dụng trong việc tính toán ma trận, ví dụ $A^{100}$ cũng chỉ tương đương với $V^{-1}\lambda^{100}V$ => giảm khối lượng tính toán rất nhiều

> nãy giờ nói term  biến đổi(transformation), biến đổi không gian vécto này sang không gian vectơ khác, thì biến đổi ở đây đơn giản là nhân hai ma trận với nhau, $A . B$, theo thứ tự này thì tức là biến đổi không gian véc tơ của B về không gian véc tơ của A, nói dễ hiểu hơn nữa tức là thể hiện một véc tơ dưới góc nhìn của không gian B sang góc nhìn của không gian A 

> Khi tìm được U và V rồi thì ứng dụng lại tính chất của Orthogonal matrix lại để tìm D<br>
> rất hay ở một chỗ  <u>D là một ma trận đường chéo(Diagonal matrix)</u> trong đó các phần tử trên đường chéo của D sẽ có giá trị giảm dần<br>
> => vì giảm dần nên ta có thể chọn K cột đầu tiên của D để xấp xỉ ma trận A ban đầu

### How to find $U, D, V$  <br>

- First, find V and U, by just find the Eigenmatrix of $A^T.A$ and $A.A^T$ <br>
- After having V and U, subtitute back to find Sigma(Diagonal Matrix) by: $D = U^T.A.V$

From this [video](https://www.youtube.com/watch?v=4tvw-1HI45s)


![SVD](utils/img/svd.png)

In [1]:
import numpy as np
from numpy.linalg import svd, eig

In [2]:
A = np.array([
    [3,1,1],
    [1,3,1],
])

In [3]:
ev_V, V = eig(A.T@A) # result is eigenvalues and eigenvectors with columns as eigenvectors

In [4]:
ev_U, U = eig(A@A.T)

In [5]:
V.round(10)

array([[-0.66666667, -0.70710678, -0.23570226],
       [-0.66666667,  0.70710678, -0.23570226],
       [-0.33333333,  0.        ,  0.94280904]])

In [6]:
U.round(10)

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [7]:
Sigma = U.T@A@V

In [8]:
Sigma.round(10)

array([[-4.24264069, -0.        , -0.        ],
       [ 0.        ,  2.        ,  0.        ]])

check lại với hàm svd xem sigma với D có giống nhau không

In [9]:
U, D, V_T = svd(A)

In [10]:
D

array([4.24264069, 2.        ])

nó lại chả giống vcl